version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: financeguy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://utilisateur:motdepasse@db:5432/financeguy
      - JWT_SECRET_KEY=votre_clé_secrète_très_complexe
    depends_on:
      - db
    volumes:
      - ./back:/app

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - /app/node_modules

volumes:
  postgres_data:
