version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
      - /app/__pycache__
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./front
      dockerfile: docker/Dockerfile
      target: dev-front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
