pipeline {
    agent { label 'dynamic-agent' }
    stages {
        stage('Terraform Init') {
            steps {
                dir('infra') {  
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('infra') {
                    sh 'terraform plan'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('infra') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
